export const productThemes = {
  read: {
    name: "OneRead",
    background: "#FFFFFF",
    accent: "#111111",
    border: "#EAEAEA",
    surface: "#FFFFFF",
    mutedText: "#6B6B6B",
  },
  article: {
    name: "OneArticle",
    background: "#F3F8FF",
    accent: "#3F6FA8",
    border: "#D8E7F8",
    surface: "#EAF3FF",
    selectedSurface: "#DDEEFF",
    mutedText: "#6B6B6B",
  },
  lingo: {
    name: "OneLingo",
    background: "#F5F1FF",
    accent: "#6F5AA8",
    border: "#DED4F5",
    surface: "#EEE7FB",
    mutedText: "#6B6B6B",
  },
  goal: {
    name: "OneGoal",
    background: "#F1FAF3",
    accent: "#3F7A4A",
    border: "#D3EBD8",
    surface: "#E7F5EA",
    mutedText: "#6B6B6B",
  },
  plate: {
    name: "OnePlate",
    background: "#FFF6F3",
    accent: "#C96457",
    border: "#F1D6D1",
    surface: "#FFEDEA",
    hover: "#FFE3DD",
    mutedText: "#6B6B6B",
  },
  move: {
    name: "OneMove",
    background: "#F3FAF5",
    accent: "#5F8C6A",
    border: "#D7EBDD",
    surface: "#EAF6EE",
    hover: "#DFF0E5",
    mutedText: "#6B6B6B",
  },
} as const;

export type ProductThemeKey = keyof typeof productThemes;
