/**
 * One Read — summary generation + cache.
 *
 * For each (TopicDailyPick, summaryLanguage, primaryTopic, difficulty) we
 * generate the summary at most once. The cache lives in the `Summary`
 * table — see `prisma/schema.prisma`.
 *
 * In production, summaries are generated by the configured LLM provider
 * (`AI_PROVIDER=openai|anthropic`) and validated against a strict JSON
 * schema. The structured object is stored in `Summary.structuredJson`
 * and rendered to bodyText / bodyHtml for the email.
 *
 * Without an LLM provider, the heuristic fallback returns the article
 * excerpt lightly framed for the user's primary topic. It is always
 * truthful (no invented content) but has no displayable richness.
 *
 * Quality bar: summaries with `confidence < MIN_SUMMARY_CONFIDENCE` are
 * persisted as `status = "REJECTED"` so we have an audit trail, but the
 * pipeline must NOT send them.
 */

import { prisma } from "./prisma";
import { topicBySlug } from "./topics";
import {
  getLlmProvider,
  type LlmProvider,
  type StructuredSummary,
} from "./llm";
import { MIN_SUMMARY_CONFIDENCE } from "./thresholds";
import type { Article, TopicDailyPick } from "@prisma/client";

export interface SummaryRequest {
  pick: Pick<
    TopicDailyPick,
    "id" | "topic" | "subtopics" | "articleTitle" | "sourceName"
  >;
  article: Pick<
    Article,
    | "title"
    | "url"
    | "rawExcerpt"
    | "cleanedText"
    | "sourceLanguage"
    | "sourceName"
  >;
  summaryLanguage: string;
  primaryTopic: string;
  difficulty: string;
}

export interface SummaryResult {
  bodyText: string;
  bodyHtml?: string;
  structured?: StructuredSummary;
  confidence?: number;
  generator?: string;
  status: "READY" | "REJECTED";
  rejectionReason?: string;
}

export interface SummaryProvider {
  id: string;
  generate(req: SummaryRequest): Promise<SummaryResult>;
}

export function createLlmSummaryProvider(
  llm: LlmProvider,
  minConfidence: number = MIN_SUMMARY_CONFIDENCE,
): SummaryProvider {
  return {
    id: llm.id,
    async generate(req: SummaryRequest): Promise<SummaryResult> {
      const structured = await llm.summarize({
        title: req.article.title,
        sourceName: req.article.sourceName,
        url: req.article.url,
        sourceLanguage: req.article.sourceLanguage,
        targetLanguage: req.summaryLanguage,
        primaryTopic: req.primaryTopic,
        difficulty: req.difficulty,
        cleanedText: req.article.cleanedText ?? null,
        rawExcerpt: req.article.rawExcerpt ?? null,
      });

      if (!structured) {
        return {
          ...heuristicResult(req),
          status: "REJECTED",
          rejectionReason: "LLM returned null or invalid JSON",
          generator: llm.id,
        };
      }

      const status: "READY" | "REJECTED" =
        structured.confidence >= minConfidence ? "READY" : "REJECTED";
      const rejectionReason =
        status === "REJECTED"
          ? `confidence ${structured.confidence} < ${minConfidence}`
          : undefined;

      const { bodyText, bodyHtml } = renderStructured(structured);
      return {
        bodyText,
        bodyHtml,
        structured,
        confidence: structured.confidence,
        generator: llm.id,
        status,
        rejectionReason,
      };
    },
  };
}

/** Stable id for the dev-only heuristic provider. Surfaced in the admin
 * so heuristic output is never mistaken for real LLM output. */
export const HEURISTIC_GENERATOR_ID = "heuristic-dev";

/** True when a generator id denotes the dev heuristic (not a real LLM). */
export function isHeuristicGenerator(generator: string | null | undefined): boolean {
  return !!generator && generator.startsWith("heuristic");
}

export const heuristicSummaryProvider: SummaryProvider = {
  id: HEURISTIC_GENERATOR_ID,
  async generate(req): Promise<SummaryResult> {
    const isProd = process.env.NODE_ENV === "production";
    if (isProd) {
      // In production we refuse to mark heuristic summaries as READY.
      // The pipeline will skip the send and the admin page will surface
      // the rejection so the misconfig is visible.
      console.error(
        "[summarizer] Heuristic provider used in production for pick",
        req.pick.id,
        "— rejecting. Configure AI_PROVIDER + API key.",
      );
      return {
        ...heuristicResult(req),
        status: "REJECTED",
        rejectionReason:
          "heuristic provider used in production (AI_PROVIDER missing or invalid)",
        generator: HEURISTIC_GENERATOR_ID,
      };
    }
    return {
      ...heuristicResult(req),
      status: "READY",
      generator: HEURISTIC_GENERATOR_ID,
    };
  },
};

function heuristicResult(req: SummaryRequest): {
  bodyText: string;
  bodyHtml: string;
} {
  const excerpt = (req.article.rawExcerpt ?? "").trim();
  const topic = topicBySlug(req.primaryTopic);
  const lang = req.summaryLanguage;

  const intro =
    lang === "Turkish"
      ? `${req.article.sourceName} kaynagindan, ${topic?.label ?? "secili konuda"} alaninda bir yazi:`
      : `From ${req.article.sourceName}, on ${topic?.label ?? "your selected topic"}:`;

  const fallback =
    lang === "Turkish"
      ? "Yazinin ozetini sabah okumak icin size bir rehber: ana fikri kisaca aktarir, gerekirse tam metne yonlendirir."
      : "A short read to start your morning: the main idea, distilled — follow the link for the full piece.";

  const body = excerpt.length > 0 ? excerpt : fallback;

  const text = `${intro}\n\n${body}`;
  const html = `
<p style="margin:0 0 14px 0;color:#6B5F50;font-size:13px;font-style:italic;">${escapeHtml(intro)}</p>
<p style="margin:0;color:#1B1612;font-size:15.5px;line-height:1.65;">${escapeHtml(body)}</p>
  `.trim();

  return { bodyText: text, bodyHtml: html };
}

export function renderStructured(s: StructuredSummary): {
  bodyText: string;
  bodyHtml: string;
} {
  const text = [
    s.oneLineHook && `"${s.oneLineHook}"`,
    "",
    s.threeSentenceSummary.filter(Boolean).join(" "),
    "",
    s.summaryLanguage === "Turkish" ? "Ozetler:" : "Key takeaways:",
    ...s.keyTakeaways.filter(Boolean).map((t) => `- ${t}`),
    "",
    s.oneThingToRemember &&
      (s.summaryLanguage === "Turkish"
        ? `Aklinda kalsin: ${s.oneThingToRemember}`
        : `Remember: ${s.oneThingToRemember}`),
  ]
    .filter((line) => line !== null && line !== undefined)
    .join("\n");

  const takeawaysHtml = s.keyTakeaways
    .filter(Boolean)
    .map(
      (t) =>
        `<li style="margin:0 0 8px 0;color:#1B1612;font-size:15px;line-height:1.55;">${escapeHtml(t)}</li>`,
    )
    .join("");

  const html = `
<div style="margin:0 0 18px 0;font-family:ui-serif,Georgia,Cambria,serif;font-style:italic;color:#6B5F50;font-size:15px;line-height:1.5;">${escapeHtml(s.oneLineHook)}</div>
<div style="margin:0 0 22px 0;font-family:ui-serif,Georgia,Cambria,serif;color:#1B1612;font-size:16px;line-height:1.65;">
  ${s.threeSentenceSummary
    .filter(Boolean)
    .map((p) => `<p style="margin:0 0 8px 0;">${escapeHtml(p)}</p>`)
    .join("")}
</div>
<div style="margin:0 0 8px 0;font-family:ui-sans-serif,system-ui,sans-serif;font-size:11.5px;letter-spacing:0.14em;text-transform:uppercase;color:#9C8F7E;">${escapeHtml(s.summaryLanguage === "Turkish" ? "One cikanlar" : "Key takeaways")}</div>
<ul style="margin:0 0 22px 18px;padding:0;">${takeawaysHtml}</ul>
${
  s.oneThingToRemember
    ? `<div style="margin:0 0 4px 0;font-family:ui-sans-serif,system-ui,sans-serif;font-size:11.5px;letter-spacing:0.14em;text-transform:uppercase;color:#9C8F7E;">${escapeHtml(s.summaryLanguage === "Turkish" ? "Aklinda kalsin" : "Remember")}</div>
<div style="margin:0;font-family:ui-serif,Georgia,Cambria,serif;color:#1B1612;font-size:15.5px;line-height:1.55;">${escapeHtml(s.oneThingToRemember)}</div>`
    : ""
}
  `.trim();

  return { bodyText: text, bodyHtml: html };
}

export async function getOrCreateSummary(
  req: SummaryRequest,
  provider?: SummaryProvider,
): Promise<SummaryResult> {
  const resolvedProvider = provider ?? defaultSummaryProvider();

  const cacheKey = {
    topicDailyPickId: req.pick.id,
    summaryLanguage: req.summaryLanguage,
    primaryTopic: req.primaryTopic,
    difficulty: req.difficulty,
  };

  const cached = await prisma.summary.findUnique({
    where: {
      topicDailyPickId_summaryLanguage_primaryTopic_difficulty: cacheKey,
    },
  });
  if (cached) {
    return {
      bodyText: cached.bodyText,
      bodyHtml: cached.bodyHtml ?? undefined,
      structured:
        (cached.structuredJson as unknown as StructuredSummary | null) ??
        undefined,
      confidence: cached.confidence ?? undefined,
      generator: cached.generator ?? undefined,
      status: (cached.status as "READY" | "REJECTED") ?? "READY",
      rejectionReason: cached.rejectionReason ?? undefined,
    };
  }

  const generated = await resolvedProvider.generate(req);

  try {
    await prisma.summary.create({
      data: {
        ...cacheKey,
        bodyText: generated.bodyText,
        bodyHtml: generated.bodyHtml ?? null,
        structuredJson:
          (generated.structured as unknown as object | undefined) ?? undefined,
        confidence: generated.confidence ?? null,
        generator: generated.generator ?? resolvedProvider.id,
        status: generated.status,
        rejectionReason: generated.rejectionReason ?? null,
      },
    });
  } catch (err) {
    const fresh = await prisma.summary.findUnique({
      where: {
        topicDailyPickId_summaryLanguage_primaryTopic_difficulty: cacheKey,
      },
    });
    if (fresh) {
      return {
        bodyText: fresh.bodyText,
        bodyHtml: fresh.bodyHtml ?? undefined,
        structured:
          (fresh.structuredJson as unknown as StructuredSummary | null) ??
          undefined,
        confidence: fresh.confidence ?? undefined,
        generator: fresh.generator ?? undefined,
        status: (fresh.status as "READY" | "REJECTED") ?? "READY",
        rejectionReason: fresh.rejectionReason ?? undefined,
      };
    }
    throw err;
  }

  return generated;
}

export function defaultSummaryProvider(
  opts: { minConfidence?: number } = {},
): SummaryProvider {
  const llm = getLlmProvider();
  return llm
    ? createLlmSummaryProvider(llm, opts.minConfidence)
    : heuristicSummaryProvider;
}

function escapeHtml(s: string): string {
  return (s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
