"use client";

import { useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";

/**
 * Unified "New Article" authoring surface for OneArticle. Two modes over the
 * same editable fields:
 *   • Write with AI — paste source material, generate an editable draft with the
 *     configured provider (real model when GEMINI_API_KEY is set; dev heuristic
 *     locally), then refine and save.
 *   • Write manually — type the issue by hand.
 *
 * Both save through the existing create-manual-issue action as an issue without
 * a source article. "Save as draft" keeps it in DRAFT (never sent); "Save as
 * ready" marks it READY for the approval/schedule workflow.
 */

type Mode = "ai" | "manual";

const SUMMARY_LANGUAGES = ["English", "Turkish", "Spanish", "French", "German"];
const SOURCE_LANGUAGES = ["English", "Turkish"];

export function NewArticleAuthor({
  topicSlugs,
  defaultDate,
  ai,
}: {
  topicSlugs: string[];
  defaultDate: string;
  ai: { statusLabel: string; blocker: string | null; productionReady: boolean; activeModel: string };
}) {
  const router = useRouter();
  const [mode, setMode] = useState<Mode>("ai");

  const [form, setForm] = useState({
    date: defaultDate,
    topic: topicSlugs[0] ?? "artificial-intelligence",
    sourceLanguage: "English",
    summaryLanguage: "English",
    title: "",
    sourceName: "Manual",
    sourceText: "",
    subject: "",
    previewText: "",
    bodyText: "",
    adminNotes: "",
  });
  const set = (k: keyof typeof form, v: string) => setForm((f) => ({ ...f, [k]: v }));

  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState<null | "DRAFT" | "READY">(null);
  const [generator, setGenerator] = useState("manual");
  const [genMeta, setGenMeta] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState<{ pickId: string; status: string } | null>(null);

  async function generate() {
    setGenerating(true);
    setError(null);
    setGenMeta(null);
    try {
      const res = await fetch("/api/admin/one-article/generate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          title: form.title,
          sourceText: form.sourceText,
          sourceName: form.sourceName,
          topic: form.topic,
          sourceLanguage: form.sourceLanguage,
          summaryLanguage: form.summaryLanguage,
        }),
      });
      const json = await res.json().catch(() => ({}));
      if (!res.ok || !json.ok) {
        setError(json.error ?? "generate_failed");
        return;
      }
      const d = json.draft as {
        subject: string;
        previewText: string;
        bodyText: string;
        status: string;
        confidence: number | null;
        generator: string;
        rejectionReason: string | null;
      };
      setForm((f) => ({
        ...f,
        subject: d.subject || f.subject,
        previewText: d.previewText || f.previewText,
        bodyText: d.bodyText || f.bodyText,
      }));
      setGenerator(d.generator || "ai");
      const conf = d.confidence != null ? ` · confidence ${d.confidence}` : "";
      setGenMeta(
        d.status === "READY"
          ? `Draft generated by ${d.generator}${conf}. Review and edit before saving.`
          : `Provider returned ${d.status}${d.rejectionReason ? ` (${d.rejectionReason})` : ""}${conf}. You can still edit and save.`,
      );
    } catch {
      setError("network_error");
    } finally {
      setGenerating(false);
    }
  }

  async function save(draft: boolean) {
    setSaving(draft ? "DRAFT" : "READY");
    setError(null);
    try {
      const res = await fetch("/api/admin/one-article/action", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          action: "create-manual-issue",
          date: form.date,
          topic: form.topic,
          sourceLanguage: form.sourceLanguage,
          summaryLanguage: form.summaryLanguage,
          title: form.title,
          sourceName: form.sourceName,
          subject: form.subject,
          previewText: form.previewText,
          bodyText: form.bodyText,
          adminNotes: form.adminNotes,
          acknowledgeNoSource: true,
          draft,
          generator: mode === "ai" ? generator : "manual",
        }),
      });
      const json = await res.json().catch(() => ({}));
      if (!res.ok || !json.ok) {
        setError(json.error ?? "save_failed");
        return;
      }
      setSaved({ pickId: json.result.pickId, status: json.result.status });
      router.refresh();
    } catch {
      setError("network_error");
    } finally {
      setSaving(null);
    }
  }

  function reset() {
    setSaved(null);
    setGenMeta(null);
    setGenerator("manual");
    setForm((f) => ({ ...f, title: "", sourceText: "", subject: "", previewText: "", bodyText: "", adminNotes: "" }));
  }

  if (saved) {
    return (
      <div className="rounded-2xl border border-admin-line bg-admin-surface p-6 shadow-admin">
        <h3 className="font-serif text-[19px] text-admin-ink">Issue saved as {saved.status}</h3>
        <p className="mt-2 text-[13px] text-admin-body">
          {saved.status === "DRAFT"
            ? "Saved as a draft. It won’t be sent until you mark it ready and approve it."
            : "Saved as ready. Approve and schedule it from the issue page to send at 07:00."}
        </p>
        <div className="mt-5 flex flex-wrap gap-2">
          <a
            href={`/admin/one-article/issues/${saved.pickId}`}
            className="rounded-full bg-admin-accent px-4 py-1.5 text-[12.5px] text-white hover:bg-admin-accent-strong"
          >
            Open issue editor
          </a>
          <button
            type="button"
            onClick={reset}
            className="rounded-full border border-admin-line-strong bg-admin-surface px-4 py-1.5 text-[12.5px] text-admin-ink hover:bg-admin-sink"
          >
            Write another
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-admin-line bg-admin-surface p-5 shadow-admin sm:p-6">
      {/* Mode toggle */}
      <div className="mb-5 inline-flex rounded-full border border-admin-line bg-admin-bg p-0.5">
        {(["ai", "manual"] as const).map((m) => (
          <button
            key={m}
            type="button"
            onClick={() => setMode(m)}
            className={`rounded-full px-4 py-1.5 text-[12.5px] transition-colors ${
              mode === m ? "bg-admin-accent text-white" : "text-admin-body hover:text-admin-ink"
            }`}
          >
            {m === "ai" ? "Write with AI" : "Write manually"}
          </button>
        ))}
      </div>

      {/* Shared meta */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <Field label="Issue date">
          <input type="date" className={inputCls} value={form.date} onChange={(e) => set("date", e.target.value)} />
        </Field>
        <Field label="Topic">
          <select className={inputCls} value={form.topic} onChange={(e) => set("topic", e.target.value)}>
            {topicSlugs.map((t) => (
              <option key={t} value={t}>{t}</option>
            ))}
          </select>
        </Field>
        <Field label="Source language">
          <select className={inputCls} value={form.sourceLanguage} onChange={(e) => set("sourceLanguage", e.target.value)}>
            {SOURCE_LANGUAGES.map((l) => <option key={l}>{l}</option>)}
          </select>
        </Field>
        <Field label="Summary (email) language">
          <select className={inputCls} value={form.summaryLanguage} onChange={(e) => set("summaryLanguage", e.target.value)}>
            {SUMMARY_LANGUAGES.map((l) => <option key={l}>{l}</option>)}
          </select>
        </Field>
      </div>

      <div className="mt-4">
        <Field label="Title">
          <input className={inputCls} value={form.title} onChange={(e) => set("title", e.target.value)} placeholder="Working title for this issue" />
        </Field>
      </div>

      {/* AI generation panel */}
      {mode === "ai" && (
        <div className="mt-5 rounded-xl border border-admin-line bg-admin-bg p-4">
          <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
            <span className="text-[11px] uppercase tracking-eyebrow text-admin-muted">Generate with AI</span>
            <span className={`text-[11.5px] ${ai.productionReady ? "text-emerald-700" : "text-admin-muted"}`}>
              {ai.productionReady ? `${ai.activeModel}` : ai.statusLabel}
            </span>
          </div>
          {ai.blocker && (
            <p className="mb-2 text-[12px] text-dawn">
              {ai.blocker}. A local draft still generates with the dev heuristic; production needs the key.
            </p>
          )}
          <Field label="Source material (paste the article text, notes, or a brief)">
            <textarea
              className={`${inputCls} h-40`}
              value={form.sourceText}
              onChange={(e) => set("sourceText", e.target.value)}
              placeholder="Paste the source content the summary should be grounded in…"
            />
          </Field>
          <div className="mt-3 flex items-center gap-3">
            <button
              type="button"
              onClick={generate}
              disabled={generating || !form.title.trim() || !form.sourceText.trim()}
              className="rounded-full bg-admin-accent px-4 py-1.5 text-[12.5px] text-white hover:bg-admin-accent-strong disabled:opacity-40"
            >
              {generating ? "Generating…" : "Generate draft"}
            </button>
            {genMeta && <span className="text-[11.5px] text-admin-body">{genMeta}</span>}
          </div>
        </div>
      )}

      {/* Editable content */}
      <div className="mt-5 space-y-4">
        <Field label="Subject line">
          <input className={inputCls} value={form.subject} onChange={(e) => set("subject", e.target.value)} placeholder="Email subject" />
        </Field>
        <Field label="Preview text">
          <input className={inputCls} value={form.previewText} onChange={(e) => set("previewText", e.target.value)} placeholder="Inbox preview snippet (optional)" />
        </Field>
        <Field label="Body">
          <textarea className={`${inputCls} h-56`} value={form.bodyText} onChange={(e) => set("bodyText", e.target.value)} placeholder="The email body. Blank lines separate paragraphs." />
        </Field>
        <Field label="Admin notes (internal, optional)">
          <textarea className={`${inputCls} h-20`} value={form.adminNotes} onChange={(e) => set("adminNotes", e.target.value)} />
        </Field>
      </div>

      {error && <p className="mt-4 text-[12.5px] text-dawn">Error: {error}</p>}

      <div className="mt-6 flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={() => save(false)}
          disabled={saving !== null}
          className="rounded-full bg-admin-accent px-5 py-2 text-[13px] font-medium text-white hover:bg-admin-accent-strong disabled:opacity-40"
        >
          {saving === "READY" ? "Saving…" : "Save as ready"}
        </button>
        <button
          type="button"
          onClick={() => save(true)}
          disabled={saving !== null || !form.title.trim()}
          className="rounded-full border border-admin-line-strong bg-admin-surface px-5 py-2 text-[13px] text-admin-ink hover:bg-admin-sink disabled:opacity-40"
        >
          {saving === "DRAFT" ? "Saving…" : "Save as draft"}
        </button>
        <span className="text-[11.5px] text-admin-muted">Saved without a source article. Nothing is sent here.</span>
      </div>
    </div>
  );
}

const inputCls =
  "block w-full rounded-lg border border-admin-line bg-admin-surface px-3 py-2 text-[13px] text-admin-ink outline-none focus:border-admin-accent";

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <label className="block">
      <span className="mb-1.5 block text-[11px] uppercase tracking-eyebrow text-admin-muted">{label}</span>
      {children}
    </label>
  );
}
